name: lexactivator_example
description: Demonstrates how to use the lexactivator plugin.


environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  lexactivator:
    path: ../


dev_dependencies:
  flutter_lints: ^1.0.0


