name: lexactivator_example
description: Demonstrates how to use the lexactivator plugin.

publish_to: "none"

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  lexactivator:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
