name: lexactivator_example
description: Demonstrates how to use the lexactivator plugin.

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  lexactivator:
    path: ../

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^1.0.0


