name: lexactivator
description: LexActivator wrapper for Dart and Flutter. The library lex_activator is part of the lex_activator package.
version: 3.0.0
homepage: https://github.com/cryptlex/lexactivator-dart

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: LexactivatorPlugin
      macos:
        pluginClass: LexactivatorPlugin
      windows:
        pluginClass: LexactivatorPlugin
      android:
        package: com.example.lexactivator
        pluginClass: LexactivatorPlugin
      ios:
        pluginClass: LexactivatorPlugin
