name: lexactivator
description: LexActivator API wrapper for Dart. Integrates Crypltex's services into the Dart language.
version: 3.33.0
homepage: https://cryptlex.com

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: LexactivatorPlugin
      macos:
        pluginClass: LexactivatorPlugin
      windows:
        pluginClass: LexactivatorPlugin
      android:
        package: com.example.lexactivator
        pluginClass: LexactivatorPlugin
      ios:
        pluginClass: LexactivatorPlugin

false_secrets:
  - '/linux/linux-aarch64/libLexActivator.so'
  - '/linux/linux-x86-64/libLexActivator.so'
  - '/windows/win-x86-64/LexActivator.dll'
  - '/windows/win-arm64/LexActivator.dll'
  - '/macos/darwin-universal/libLexActivator.dylib'
