name: lexactivator
description: LexActivator API wrapper for Dart. Integrates Crypltex's services into the Dart language.
version: 3.0.0
homepage: https://cryptlex.com

environment:
  sdk: ">=2.14.0 <3.0.0"
  # flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ffigen: ^4.0.0  

dev_dependencies:
  flutter_lints: ^1.0.0
  
  
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: LexactivatorPlugin
      macos:
        pluginClass: LexactivatorPlugin
      windows:
        pluginClass: LexactivatorPlugin
